version: "3.0"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - "data:/workspace/data"
      - "runs:/workspace/runs"
    command: jupyter-lab
  tensorboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6006:6006"
    volumes:
      - "data:/workspace/data"
      - "runs:/workspace/runs"
    command: tensorboard --logdir=runs
volumes:
  data:
  runs: