version: "3.0"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - "data:/workspace/data"
      - "model:/workspace/model"
      - "runs:/workspace/runs"
    command: jupyter-lab
volumes:
  data:
  runs:
